
[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ec4899"
backgroundColor = "#0a0a0c"
secondaryBackgroundColor = "#0d0d11"
textColor = "#ffffff"
font = "sans serif"
